from typing import Dict

from fake_useragent import UserAgent


class GetUserAgent:
    """
    A class for retrieving random User-Agent headers for web scraping.
    """

    def __init__(self) -> None:
        """
        Initializes the GetUserAgent object.
        Sets up the UserAgent instance.
        """
        self.user_agent = UserAgent()

    @property
    def headers_dict(self) -> Dict[str, "UserAgent"]:
        """
        Returns a dictionary containing the User-Agent header.
        Returns:
            dict: A dictionary with the 'User-Agent' key and the random user agent generated by the UserAgent instance.
        """

        return {'User-Agent': self.user_agent.random}
